name: Node CI for app development

on:
  push:
    branches-ignore:
      - release/**
      - rc/**
      - changeset-release/**
      - mergify/merge-queue/**
      - tmp-mergify/merge-queue/**
    paths:
      - .github/mergify.yml
      - .github/workflows/ci-app.yml
      - biome.json
      - tsconfig.base.json
      - turbo.json
      - pnpm-lock.yaml
      - package.json
      - apps/app/**
      - '!apps/app/docker/**'
      - packages/**
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - .github/mergify.yml
      - .github/workflows/ci-app.yml
      - biome.json
      - tsconfig.base.json
      - turbo.json
      - pnpm-lock.yaml
      - package.json
      - apps/app/**
      - '!apps/app/docker/**'
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  ci-app-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Cache/Restore dist
        uses: actions/cache@v4
        with:
          path: |
            **/.turbo
            **/dist
            **/node_modules/.cache/turbo
          key: dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-${{ github.sha }}
          restore-keys: |
            dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Install dependencies
        run: |
          pnpm add turbo --global
          pnpm install --frozen-lockfile

      - name: Lint
        run: |
          turbo run lint --filter=@growi/app --filter=./packages/*

      - name: Slack Notification
        uses: weseek/ghaction-slack-notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Node CI for growi - lint (${{ matrix.node-version }})*'
          channel: '#ci'
          isCompactMode: true
          url: ${{ secrets.SLACK_WEBHOOK_URL }}


  ci-app-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        mongodb-version: ['6.0', '8.0']

    services:
      mongodb:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017/tcp

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - &setup-node-step
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - &cache-restore-dist-step
        name: Cache/Restore dist
        uses: actions/cache@v4
        with:
          path: |
            **/.turbo
            **/dist
            **/node_modules/.cache/turbo
          key: dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-${{ github.sha }}
          restore-keys: |
            dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-

      - &install-dependencies-step
        name: Install dependencies
        run: |
          pnpm add turbo --global
          pnpm install --frozen-lockfile

      - name: Test (app - unit & component)
        run: |
          turbo run test:unit test:components --filter=@growi/app --env-mode=loose
        env:
          MONGO_URI: mongodb://localhost:${{ job.services.mongodb.ports['27017'] }}/growi_test

      - name: Test (packages)
        run: |
          turbo run test --filter=./packages/* --env-mode=loose


      - name: Slack Notification
        uses: weseek/ghaction-slack-notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Node CI for growi - test (${{ matrix.node-version }})*'
          channel: '#ci'
          isCompactMode: true
          url: ${{ secrets.SLACK_WEBHOOK_URL }}


  ci-app-test-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        mongodb-version: ['8.0']
        elasticsearch-version:
          - env: 8
            stack-version: '8.19.16'
          - env: 9
            stack-version: '9.3.3'

    # [MEMO] Elasticsearch is started in a step to install plugins before starting it.
    services:
      mongodb:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017/tcp

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - *setup-node-step

      - *cache-restore-dist-step

      - *install-dependencies-step

      - name: Start Elasticsearch with plugins
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{ matrix.elasticsearch-version.stack-version }}
          plugins: |
            analysis-kuromoji
            analysis-icu
          security-enabled: false

      - name: Wait for Elasticsearch to be ready
        run: |
          curl \
            --no-progress-meter \
            -X GET \
            --retry 60 \
            --retry-delay 1 \
            --retry-connrefused \
            http://localhost:9200/_cluster/health?wait_for_status=green

      - name: Test
        run: |
          turbo run test:integ --filter=@growi/app --env-mode=loose
        env:
          MONGO_URI: mongodb://localhost:${{ job.services.mongodb.ports['27017'] }}/growi_test
          VITE_ELASTICSEARCH_URI: http://localhost:9200/growi
          VITE_ELASTICSEARCH_VERSION: ${{ matrix.elasticsearch-version.env }}

      - name: Slack Notification
        uses: weseek/ghaction-slack-notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Node CI for growi - test-es (${{ matrix.node-version }})*'
          channel: '#ci'
          isCompactMode: true
          url: ${{ secrets.SLACK_WEBHOOK_URL }}


  ci-app-launch-dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        mongodb-version: ['6.0', '8.0']

    services:
      mongodb:
        image: mongo:${{ matrix.mongodb-version }}
        ports:
          - 27017/tcp

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Cache/Restore dist
        uses: actions/cache@v4
        with:
          path: |
            **/.turbo
            **/dist
            **/node_modules/.cache/turbo
          key: dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-${{ github.sha }}
          restore-keys: |
            dist-ci-app-${{ runner.OS }}-node${{ matrix.node-version }}-

      - name: Install dependencies
        run: |
          pnpm add turbo --global
          pnpm install --frozen-lockfile

      - name: turbo run launch-dev:ci
        working-directory: ./apps/app
        run: |
          cp config/ci/.env.local.for-ci .env.development.local
          turbo run launch-dev:ci --env-mode=loose
        env:
          MONGO_URI: mongodb://localhost:${{ job.services.mongodb.ports['27017'] }}/growi_dev

      - name: Slack Notification
        uses: weseek/ghaction-slack-notification@master
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: '*Node CI for growi - launch-dev (${{ matrix.node-version }})*'
          channel: '#ci'
          isCompactMode: true
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
